# Generated by Django 3.2.8 on 2021-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('TEACHING', 'Teaching'), ('PERFORMANCE', 'Performance'), ('EQUIPMENT', 'Equipment hire')], max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=50)),
                ('dates', models.JSONField()),
                ('times', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('budget', models.CharField(choices=[('100-200', '100-200'), ('200-300', '200-300'), ('300-400', '300-400'), ('400+', '400+')], max_length=32)),
                ('equipment', models.JSONField()),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
    ]
