# Generated by Django 3.2.8 on 2021-12-08 20:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_address'),
        ('booking', '0006_admincontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('TEACHING', 'Teaching'), ('PERFORMANCE', 'Performance'), ('EQUIPMENT', 'Equipment hire')], max_length=32)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=50)),
                ('date_submitted', models.DateField(default=datetime.date.today)),
                ('booking_details', models.JSONField()),
                ('confirmed', models.BooleanField(default=False)),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
