# Generated by Django 3.2.8 on 2021-12-09 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_address'),
        ('booking', '0009_auto_20211209_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenthiredetails',
            name='performance_type',
        ),
        migrations.RemoveField(
            model_name='equipmenthiredetails',
            name='session_cost',
        ),
        migrations.AddField(
            model_name='equipmenthiredetails',
            name='equipment_hired',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmenthiredetails',
            name='pick_up_time',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmenthiredetails',
            name='return_time',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeachingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=32)),
                ('time', models.TimeField(blank=True)),
                ('instrument', models.CharField(choices=[('DRUM KIT', 'Drum Kit'), ('PERCUSSION', 'Percussion'), ('DULCIMER', 'Dulcimer'), ('BODHRAN', 'Dulcimer'), ('OTHER', 'Other')], max_length=32)),
                ('lesson_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('Address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.address')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
    ]
