# Generated by Django 3.2.8 on 2021-12-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20211211_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancedetails',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancedetails',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
