# Generated by Django 3.2.8 on 2021-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20211218_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancedetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='performancedetails',
            name='time',
        ),
        migrations.AddField(
            model_name='performancedetails',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancedetails',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
