# Generated by Django 3.2.8 on 2022-01-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_address'),
        ('booking', '0014_auto_20211218_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='equipmenthiredetails',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_hire', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='performancedetails',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='teachingdetails',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to='booking.booking'),
        ),
    ]
