# Generated by Django 3.2.8 on 2022-01-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20220129_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmenthiredetails',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='performancedetails',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='teachingdetails',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
