# Generated by Django 3.2.8 on 2022-01-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_teachingdetails_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingdetails',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingdetails',
            name='student_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
