# Generated by Django 3.2.8 on 2022-01-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_teachingdetails_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingInstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=32)),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('lesson_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('teaching_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.teachingdetails')),
            ],
        ),
    ]
