# Generated by Django 3.2.8 on 2022-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_booking_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancedetails',
            name='concert_dress',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
