# Generated by Django 3.2.8 on 2022-03-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_rename_time_teachinginstances_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachinginstances',
            name='duration',
        ),
        migrations.AddField(
            model_name='teachinginstances',
            name='finish',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
