# Generated by Django 3.2.8 on 2022-03-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_auto_20220306_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachingInstances',
        ),
    ]
