# Generated by Django 3.2.8 on 2022-03-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_delete_teachinginstances'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('lesson_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('teaching_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.teachingdetails')),
            ],
        ),
    ]
