# Generated by Django 3.2.8 on 2022-03-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_address'),
        ('booking', '0026_teachinginstance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentHireDetails',
            new_name='EquipmentHireDetail',
        ),
        migrations.RenameModel(
            old_name='PerformanceDetails',
            new_name='PerformanceDetail',
        ),
        migrations.RenameModel(
            old_name='TeachingDetails',
            new_name='TeachingDetail',
        ),
    ]
