# Generated by Django 3.2.8 on 2022-08-07 15:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_address_options'),
        ('booking', '0028_booking_booking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_details',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='confirmed',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=32)),
                ('booking_type', models.CharField(choices=[('TEACHING', 'Teaching'), ('PERFORMANCE', 'Performance'), ('EQUIPMENT', 'Equipment hire'), ('TEACHING AND EQUIPMENT', 'Teaching and Equipment hire')], max_length=32)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=50)),
                ('date_submitted', models.DateField(default=datetime.date.today)),
                ('booking_details', models.JSONField()),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='profiles.userprofile')),
            ],
        ),
    ]
